### ISSUE TITLE
TopKDecoder may not be GPU-safe

### ISSUE THREAD

**Issue by markriedl** [IBM/pytorch-seq2seq#102]
I may not be setting TopKDecoder up right, but it throws a lot of exceptions involving mismatches between torch.FloatTensor and torch.cuda.FloatTensor. Looks like if the encoder data is in the GPU then TopKDecoder is unhappy.

**Comment by shubhamagarwal92** [comment]
Any updates on this?

**Comment by pskrunner14** [comment]
@shubhamagarwal92 yes it's been resolved in #161
