### ISSUE TITLE
RuntimeError when running Samplescript without attention

### ISSUE THREAD

**Issue by dieuwkehupkes** [IBM/pytorch-seq2seq#109]
When I try to run the sample script with use_attention set to False I get the following error:

RuntimeError: invalid argument 1: input is not contiguous at /pytorch/torch/lib/TH/generic/THTensor.c:231

I solved it by replacing line 105 in the decoder class with

`predicted_softmax = function(self.out(output.contiguous().view(-1, self.hidden_size))).view(batch_size, output_size, -1)`

I don't have the time to do a pull request atm, but I wondered if you think this is a correct solution.

**Comment by kylegao91** [comment]
Fixed in #112
