### ISSUE TITLE
Resume checkpoints does not work. 

### ISSUE THREAD

**Issue by Deepblue129** [IBM/pytorch-seq2seq#11]
https://github.com/IBM/pytorch-seq2seq/blob/master/seq2seq/util/checkpoint.py#L87 Tries to load the directory where the checkpoint was saved in resulting in the IO error `IOError: [Errno 21] Is a directory:`

Command:
`python examples/sample.py --train_path $TRAIN_PATH --dev_path $DEV_PATH --resume --load_checkpoint 2017_07_10_19_26_58/`

Error:
```
loading checkpoint...
Loading checkpoints from ./experiment/checkpoints/2017_07_10_19_26_58/
Traceback (most recent call last):
  File "examples/sample.py", line 41, in <module>
    checkpoint = Checkpoint.load(checkpoint_path)
  File "/root/pytorch-seq2seq/seq2seq/util/checkpoint.py", line 87, in load
    model = torch.load(path)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 227, in load
    f = open(f, 'rb')
IOError: [Errno 21] Is a directory: './experiment/checkpoints/2017_07_10_19_26_58
```/

**Comment by Deepblue129** [comment]
Was able to fix this:
By changing https://github.com/IBM/pytorch-seq2seq/blob/master/seq2seq/util/checkpoint.py#L87 to `Seq2seq.load(path)`.

**Comment by kpfadnis** [comment]
@Deepblue129 I think `Seq2seq.load()` is a correct direction but path has to be adjusted as well.

**Comment by kylegao91** [comment]
@kpfadnis You don't want to change it to `Seq2seq.load` because that ties checkpoint to the `Seq2seq` class.    Checkpoint should be agnostic of the used model.  Remove the `save` and `load` methods in `Seq2seq` and use torch to save/load it.
