### ISSUE TITLE
checkpoint_every is for batch num not the epoch num?

### ISSUE THREAD

**Issue by zenghsh3** [IBM/pytorch-seq2seq#115]
https://github.com/IBM/pytorch-seq2seq/blob/96c6033f957806131b98391f64fc1f488b1fd2b7/seq2seq/trainer/supervised_trainer.py#L26

https://github.com/IBM/pytorch-seq2seq/blob/96c6033f957806131b98391f64fc1f488b1fd2b7/seq2seq/trainer/supervised_trainer.py#L119

**Comment by tejaswini** [comment]
You are right. We are checkpointing after every n batches. We will update the comment. Thanks for pointing out.

**Comment by zenghsh3** [comment]
OK
