### ISSUE TITLE
Why the comment of decoder output and seq2seq output is different?

### ISSUE THREAD

**Issue by zenghsh3** [IBM/pytorch-seq2seq#117]
https://github.com/IBM/pytorch-seq2seq/blob/96c6033f957806131b98391f64fc1f488b1fd2b7/seq2seq/models/seq2seq.py#L25

https://github.com/IBM/pytorch-seq2seq/blob/96c6033f957806131b98391f64fc1f488b1fd2b7/seq2seq/models/DecoderRNN.py#L55

**Comment by tejaswini** [comment]
Hey,
  Thanks for pointing it out. The comments have to be the same. We will fix it.
