### ISSUE TITLE
Future proof w/ torchtext

### ISSUE THREAD

**Issue by Deepblue129** [IBM/pytorch-seq2seq#12]
Much like Pytorch released [pytorch/vision](https://github.com/pytorch/vision) to be a utility library for vision projects. There is active work on [pytorch/text](https://github.com/pytorch/text). 

The current IBM repo reimplements some of the utilities provided in `pytorch/text` in the `seq2seq/dataset` directory. The design of the objects defined in `seq2seq/dataset` does not align with `pytorch/text`.

To future proof this repo, I think it will be important to either add `pytorch/text` or to design `seq2seq/dataset` similar to `pytorch/text`.

It's important that when `pytorch/text` is released to pip that it can be a drop in replacement for `seq2seq/dataset`.

**Comment by kylegao91** [comment]
@Deepblue129 This is good suggestion.  We will consider using/mimicking it in the next version.

**Comment by kylegao91** [comment]
I have had a look at pytorch/text, my assessment is that it's not ready to be used.  My suggestion is that we proceed by designing dataset similar to their interface before it gets ready.  @kpfadnis @avinash2692  Thoughts?
