### ISSUE TITLE
decoder hidden size 

### ISSUE THREAD

**Issue by ShilinHe** [IBM/pytorch-seq2seq#121]
Hi, Thanks for your great work on seq2seq. I have a question regarding the hidden size of DecoderRNN.

In the code of DecoderRNN, 
decoder_hidden = self._init_state(encoder_hidden),
whose size is (#layers, #batch, #directions * hidden_size), the last dimension is 2*hidden_size if we use bidirectional in encoder. 
However, in the implementation of forward_step, 
output, hidden = self.rnn(embedded, hidden), which takes decoder_hidden as initial input, 
the hidden size of rnn is hidden_size, which is not 2*hidden_size, I am sort of confused, do they have to be the same?

Thanks!

**Comment by kylegao91** [comment]
The hidden size is passed at init time, look at [here](https://github.com/IBM/pytorch-seq2seq/blob/master/examples/sample.py#L103).
