### ISSUE TITLE
TopKDecoder doesn't work on batch size > 1

### ISSUE THREAD

**Issue by jacklanchantin** [IBM/pytorch-seq2seq#122]
The inflate on the the hidden state and the encoder outputs is incorrect. 

If the original hidden state has length 3 and a batch size of 2, it will look like this:

[ABC
 DEF]

And the current inflate does this (for a beam size of 2):

[ABC
 DEF]
[ABC
 DEF]

But it should actually be:

[ABC
 ABC]
[DEF
 DEF]

**Comment by kylegao91** [comment]
Actually expanding [A;B] to [A;B;A;B] is expected, because each beam is indexed by `idx / batch_size + beam_idx`.
