### ISSUE TITLE
Suggestion for Word Embedding

### ISSUE THREAD

**Issue by Jackberg** [IBM/pytorch-seq2seq#124]
Thanks for you generous efforts on this implementation! Here's a small advice.

If I understood correctly, the dimension of word embeddings used in class EncoderRNN and DecoderRNN is set to the hidden_size. But in some conditions, like dialogue modelling, we may use 1000 hidden units, but we don't want to use 1000 as the dimension of word embeddings, right?

So I advise you to add a parameter embedding_dim (with some default value or use hidden_size as it's default), so that we can choose it as other hyper parameters.

Cheers!

**Comment by kylegao91** [comment]
Good suggestion!  We will work on this (sorry for the late reply, has been busy).
