### ISSUE TITLE
a  Implicit bug : batch_size = encoder_hidden[0].size(1) 

### ISSUE THREAD

**Issue by yucoian** [IBM/pytorch-seq2seq#126]
The function    def _validate_args(... )  in pytorch-seq2seq/seq2seq/models/DecoderRNN.py , line 197 " batch_size = encoder_hidden[0].size(1) ", is a bug obviously, please check it. 

The doc about it is "- **encoder_hidden** (num_layers * num_directions, batch_size, hidden_size): tensor containing the features in the hidden state `h` of encoder. Used as the initial hidden state of the decoder. (default `None`)"

**Comment by kylegao91** [comment]
It's not a bug because when the RNN is LSTM, `encoder_hidden` is actually a tuple `(h_n, c_n)`.  Please refer [here](http://pytorch.org/docs/0.3.1/nn.html#torch.nn.LSTM) for detail.

**Comment by yucoian** [comment]
OK, a really nice explanation. Thanks a lot!
