### ISSUE TITLE
Dataset format confusion.

### ISSUE THREAD

**Issue by CaptainEven** [IBM/pytorch-seq2seq#128]
Hi, Thx for your work. I think it‘s really interesting! I recently have worked on Chinese text summarization, how should i organize(or format) the dataset, do you haev any suggestion？

**Comment by CaptainEven** [comment]
Because i'm confused about thre dataset from toy dataset.

**Comment by CaptainEven** [comment]
Because i 'm confused about the dataset from toy dataset like this:
4 2 2 9 9	9 9 2 2 4
4 4 2 0	0 2 4 4
1 1 9 0 3 4	4 3 0 9 1 1
9	9
2 7 3	3 7 2
1 5 7	7 5 1
0 8 6 1 4 2	2 4 1 6 8 0
6 8 7	7 8 6
1 8 9 2 1	1 2 9 8 1
7 7	7 7
8	8
And, what's the difference and connections for train and dev datasets here.

**Comment by kylegao91** [comment]
Please refer torchtext for data format questions.
