### ISSUE TITLE
Use pretrained embeddings

### ISSUE THREAD

**Issue by TeodorMoiseev** [IBM/pytorch-seq2seq#132]
Hello, 

As I understood, there is no possibility to use pretrained embeddings for words such as word2vec or GloVe now. Can you add this functionality?

Thank you

**Comment by kylegao91** [comment]
@TeodorMoiseev I made changes that allow pre-trained embedding in #135.  Can you try and let me know if it works for you?

FYI, to load the pre-trained embedding and make sure that word indices match, you can use `torchtext.vocab.load_vectors`.

**Comment by femoiseev** [comment]
Sorry for delay, I tried and it works well for me. Thank you!
