### ISSUE TITLE
In TopKDecoder.py , line 50, docs of "input" is misleading

### ISSUE THREAD

**Issue by yucoian** [IBM/pytorch-seq2seq#139]
Detail:
**inputs** (seq_len, batch, input_size): list of sequences, whose length is the batch size and within which  each sequence is a list of token IDs.  It is used for teacher forcing when provided. (default is `None`)

Note: The shape of  inputs is (seq_len, batch, input_size) ,which contradicts  the description of inputs.

**Comment by pskrunner14** [comment]
@yucoian list of sequences (seq_len), whose length is the batch size (batch) and within which each sequence is a list of token IDs (input_size).

**Comment by yucoian** [comment]
Thanks~
