### ISSUE TITLE
README Add test instructions.

### ISSUE THREAD

**Issue by Deepblue129** [IBM/pytorch-seq2seq#14]
It's unclear in the README what command to run the tests. Found it in the `.travis.yml` file:
`nosetests --with-coverage --cover-erase --cover-package=seq2seq`

In addition, the requirements.txt does not include development packages like `nose`. It would be helpful if the README covered how to install the required packages to run the tests.

**Comment by kylegao91** [comment]
Opened new issue #18 to cover this.
