### ISSUE TITLE
Teacher_forcing does not work when using TopKDecoder

### ISSUE THREAD

**Issue by ZhuoranLyu** [IBM/pytorch-seq2seq#150]
Hi, I did not see where the teacher_forcing is used when using TopKDecoder.

**Comment by pskrunner14** [comment]
@ZhuoranLyu we only train the `DecoderRNN` which uses teacher_forcing and later we pass the trained decoder to the `TopKDecoder` for prediction as follows:
```
decoder = TopKDecoder(seq2seq.decoder, k)
```

**Comment by pskrunner14** [comment]
Closing this for now
