### ISSUE TITLE
Cuda.LongTensor instead of LongTensor on GPU

### ISSUE THREAD

**Issue by ShilinHe** [IBM/pytorch-seq2seq#156]
I found this bug when running the basic script, example/sample.py:

return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of type torch.cuda.LongTensor but found type torch.LongTensor for argument #3 'index'

It seems to be a wrong type of tensor on GPU.

**Comment by pskrunner14** [comment]
@ShilinHe can you provide the complete log? Seems like the tensor is'nt being assigned to cuda.

**Comment by cailurus** [comment]
same

**Comment by pskrunner14** [comment]
@ShilinHe this has been fixed in #161.

**Comment by ShilinHe** [comment]
So sorry for the late reply, Thanks for your work!

**Comment by DavidLKing** [comment]
Heads up, I'm getting the same errors after a fresh clone. I've been manually adding `if torch.cuda.is_available(): VARIABLE.cuda()` entries to get around it temporarily.
