### ISSUE TITLE
can I use pytorch-seq2seq implement this model

### ISSUE THREAD

**Issue by gaikin** [IBM/pytorch-seq2seq#157]
![decoder](https://user-images.githubusercontent.com/16111190/44331043-168c9c00-a49b-11e8-8281-7f10dee9d057.jpeg)

which was celled encoder-decoder with feedback

**Comment by pskrunner14** [comment]
@gaikin yes you can implement encoder-decoder (autoencoder) for seq2seq tasks with attention and beam search in [pytorch-seq2seq](https://github.com/IBM/pytorch-seq2seq). Not sure what you mean by feedback exactly, as the model seems like a generic encoder-decoder arch with attention.
