### ISSUE TITLE
How is the memory optimized when using pre-trained embeddings like FastText and etc?

### ISSUE THREAD

**Issue by rrkarim** [IBM/pytorch-seq2seq#170]
I'm trying to use fasttext-en as my embedding for the encoder but I get out of memory error by CUDA. Does the model optimize the memory usage for the pre-trained embeddings like creating dictionaries as an example? My embeddings shape is: (2*10^6, 300)

**Comment by pskrunner14** [comment]
@CoderINusE there is no memory optimization as of now. The embedding layer weights are initialized with the embeddings you provide if you choose to do so. However you could refer to [this](https://discuss.pytorch.org/t/cuda-out-of-memory/449) thread for more info on how to manage memory with large variable sizes in PyTorch.
