### ISSUE TITLE
GPU Tesla P100 vs Intel i7 CPU. GPU is only 2x faster.

### ISSUE THREAD

**Issue by Deepblue129** [IBM/pytorch-seq2seq#3]
Only a 2x speed up on a P100 Tesla vs a Intel i7 CPU

GPU:
Time elapsed: 4m 36s, Progress: 8%, Train Perplexity: 1.1057

CPU:
Time elapsed: 4m 1s, Progress: 3%, Train Perplexity: 1.1451

Running the on SimpleQuestion dataset.

**Comment by kylegao91** [comment]
@Deepblue129 Thanks for the feedback.  We are working on benchmarks on both effectiveness and efficiency performances, and we will try to optimize w.r.t. the benchmarks.

**Comment by Deepblue129** [comment]
@kylegao91 Forked the version online. I've made it faster on my system by incorporating ideas from other libraries. 

The README mentions, "For major contributions and new features, please discuss with the collaborators in corresponding issues.". How should I go about doing that?

**Comment by kylegao91** [comment]
@Deepblue129 Could you please elaborate a bit about the ideas you incorporated?  You are welcome to make a pull request as well.  Thanks in advance.

**Comment by Deepblue129** [comment]
@kylegao91 Looking to send pull requests for all the ideas that I've sent issues about. Looking into the policies of me contributing on the behalf of my company before I can!
