### ISSUE TITLE
size_average=False

### ISSUE THREAD

**Issue by Deepblue129** [IBM/pytorch-seq2seq#41]
https://github.com/IBM/pytorch-seq2seq/blob/master/seq2seq/loss/loss.py#L108

If `size_average=False`, shouldn't the get_loss return without dividing by the normalization term?

**Comment by kylegao91** [comment]
@Deepblue129 Good catch.  I somehow thought `size_average` means averaging over time steps...  I shouldn't have affected Perplexity though..
