### ISSUE TITLE
Docs of dimensions of decoder RNN are wrong

### ISSUE THREAD

**Issue by kylegao91** [IBM/pytorch-seq2seq#50]
* `inputs` should have size `(batch_size, seq_len, hidden_size)` since RNN is set to be batch first.
* `encoder_hidden` should be `(num_layers * num_direction, batch_size, hidden_size)`
* `decoder_outputs` should be `(seq_len, batch_size, vocab_size)`

**Comment by yucoian** [comment]
I also think the docs  are easily misleading in decoderRNN especially.  I suggest add more description on the decoderRNN class's member function , its inputs and outputs. The rest docs are really nice.
