### ISSUE TITLE
Compatibility of TopKDecoder with DecoderRNN

### ISSUE THREAD

**Issue by abhiskk** [IBM/pytorch-seq2seq#76]
The codebase contains a `TopKDecoder` which can be used to do beam search while generating sentences. According to the docstring, the `__init__` method takes as input a `DecoderRNN` object but the code is accessing attributes like `.lang` and `.SOS_token_id` which are not present in the `DecoderRNN` class.

Also my understanding is that the `TopKDecoder` can be used to generate sentences after the `DecoderRNN` has been trained. Is this understanding correct.

**Comment by kylegao91** [comment]
Hi @abhiskk , sorry for the late reply.  Yes your understanding is correct.  However TopKDecoder is a bit outdated...  We will fix it and let you know.

**Comment by abhiskk** [comment]
Thanks @kylegao91, appreciate it. 👏 for the work on repository, I am having a good time working with the codebase.

**Comment by kylegao91** [comment]
@abhiskk Would you like to try the updated code in `topk`?  There should be example usage in `scripts/integration_test.py`.

**Comment by surajit-techie** [comment]
I looked up `scripts/integration_test.py` in `topk` branch, but the `Predictor` does not return top-k sequences when the `Seq2Seq` object with `TopKDecoder` is used. 

How do I get `topk` predictions using the updated `TopKDecoder`?

**Comment by kylegao91** [comment]
@surajit-techie Sorry the documentation hasn't been updated yet.  Supposed you call the topk decoder as `outputs, hidden, info = model(...)`, the top K sequences are stored in `info['topk_sequence']`.   It is documented at [here](https://github.com/IBM/pytorch-seq2seq/blob/c5ccf32987f3728bd33700ac64241075a42bddf5/seq2seq/models/TopKDecoder.py#L72).

**Comment by donlee90** [comment]
When you run seq2seq with TopKDecoder for a batch of input sequences, the topk_sequence seems to contain only a single beam.
