### ISSUE TITLE
The order of forward of DecoderRNN is not consist with the DOC

### ISSUE THREAD

**Issue by liuq901** [IBM/pytorch-seq2seq#82]
In the code of DecoderRNN, the parameter order of forward function is 
`def forward(self, inputs=None, encoder_hidden=None, function=F.log_softmax, encoder_outputs=None, teacher_forcing_ratio=0):`
but in the document the order is 
`Inputs: inputs, encoder_hidden, encoder_outputs, function, teacher_forcing_ratio`

**Comment by kylegao91** [comment]
Good catch!  Please feel free to go ahead to fix it if you'd like to.

**Comment by liuq901** [comment]
See pull request #85
