### ISSUE TITLE
step_attn is not subscriptable

### ISSUE THREAD

**Issue by lifengjin** [IBM/pytorch-seq2seq#89]
https://github.com/IBM/pytorch-seq2seq/blob/aa27edaa1e0263928d712440c6ed49df0f1dd08a/seq2seq/models/DecoderRNN.py#L162-L170

Here Line 169 wants to slice the attn variable, but if you are using teacher_forcing but not attention, attn will be None, thus throwing out an error. Simply changing it to the following fixes this:
```
                if attn:
                    step_attn = attn[:, di, :]
                else:
                    step_attn = None
```

**Comment by kylegao91** [comment]
Yes it's a bug.  Please feel free to make a PR.
